### ISSUE TITLE
Issues in RPM structure

### ISSUE THREAD

**Issue by loicdescotte** [sbt/sbt-launcher-package#73] opened 2014-09-11 14:11 UTC
The RPM provided on scala-sbt.org has a few issues 

Running 'rpm -qpl sbt-0.13.5.rpm', we have the following results 

``` bash
$ rpm -qpl sbt-0.13.5.rpm
/etc/sbt-launcher-packaging
/usr
/usr/bin/sbt
/usr/share
/usr/share/doc
/usr/share/doc/sbt
/usr/share/doc/sbt/copyright
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/sbt.1.gz
/usr/share/sbt-launcher-packaging/bin
/usr/share/sbt-launcher-packaging/bin/sbt
/usr/share/sbt-launcher-packaging/bin/sbt-launch-lib.bash
/usr/share/sbt-launcher-packaging/bin/sbt-launch.jar
/usr/share/sbt-launcher-packaging/conf
/usr/share/sbt-launcher-packaging/conf/sbtconfig.txt
/usr/share/sbt-launcher-packaging/conf/sbtopts
```

The RPM should not own the following directories (and erase their user rights) : 

``` bash
/usr
/usr/share
/usr/share/doc
/usr/share/man
/usr/share/man/man
```

This folders are provided by the `filesystem` system on Red Hat distributions, it can be dangerous to override this.

I didn't find the RPM spec file on github. I've opened another issue about its availability so we would be able to offer some patches :  https://github.com/sbt/sbt-launcher-package/issues/74

Thanks

**Comment by jsuereth** [comment] 2015-03-03 13:23
This is a super interesting problem (sorry for taking so long to respond).  I think this needs to be opened against sbt-native-packager (which we use to build our RPM).

You'll want to modify the linuxPackageMapping config in sbt: https://github.com/sbt/sbt-launcher-package/blob/master/project/packaging.scala#L129-L133


As for the RPM spec, it's generated on the fly by sbt-native-packager, so that's where we need to attack the issue.   I was trying to find more information on permission in fedora here.   Right now we assume we can use the same permissions/users for all linux packages, but it seems we may need to deviate.  We can do so just in thi sproject, but we may want ot feed the info upstream to sbt-native-packager too.

**Comment by Fnux** [comment] 2017-09-20 18:16
Why everything is in `/usr/share` ? It doesn't makes any sense.

**Comment by Fnux** [comment] 2017-09-20 18:18
Ow sorry, it's a more 'recent' issue : 

```~ » rpm -ql sbt     
/usr
/usr/share
/usr/share/doc
/usr/share/doc/sbt
/usr/share/doc/sbt/copyright
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/sbt.1.gz
/usr/share/sbt/bin
/usr/share/sbt/bin/java9-rt-export.jar
/usr/share/sbt/bin/sbt
/usr/share/sbt/bin/sbt-launch-lib.bash
/usr/share/sbt/bin/sbt-launch.jar
/usr/share/sbt/conf
/usr/share/sbt/conf/sbtconfig.txt
/usr/share/sbt/conf/sbtopts
~ » dnf info sbt
Last metadata expiration check: 1:36:49 ago on Wed 20 Sep 2017 18:39:54 CEST.
Installed Packages
Name         : sbt
Version      : 1.0.2
Release      : 0
Arch         : noarch
Size         : 1.2 M
Source       : sbt-1.0.2-0.src.rpm
Repo         : @System
From repo    : bintray--sbt-rpm
Summary      : sbt, the interactive build tool
URL          : http://github.com/sbt/sbt-launcher-package
License      : BSD
Description  : This script provides a native way to run sbt,
             :   a build tool for Scala and more.


```

**Comment by Fnux** [comment] 2017-09-20 18:20
I'm not sure if it's the 'right' issue but it's indeed an structure issue with the RPM package, and this one's still open. The package was installed via http://www.scala-sbt.org/0.13/docs/Installing-sbt-on-Linux.html.

> Note: Please report any issues with these to the sbt-launcher-package project.

**Comment by LucasMembrane** [comment] 2018-01-13 21:07
Here is my experience trying to install sbt on korara linux, which is pretty much the same as fedora 26. I may have previously installed scala from the repos, and I had previously installed sbt from the repos, but it was not in a working condition on my machine, so I went back to the scala getting started (from the command line) page, which directed my first to the sbt getting started pages, which I tried to follow, ie:
In my downloads  folder:

$ su -p
# curl https://bintray.com/sbt/rpm/rpm | sudo tee /etc/yum.repos.d/bintray-sbt-rpm.repo

That finishes immediately.

# ls -l -t /etc/yum.repos.d | more

This shows 

-rw-r--r--. 1 root root  160 Jan 13 11:51 bintray-sbt-rpm.repo

Then

# sudo yum install sbt

This displays:

    Last metadata expiration check: 0:02:10 ago on Sat 13 Jan 2018 11:57:24 AM PST.
    Package sbt-0.13.1-8.fc24.1.noarch is already installed, skipping.
    Dependencies resolved.
    Nothing to do.
    Complete!
    
However, trying to run sbt

# sbt 

    /usr/bin/sbt: line 3: [: too many arguments
    /usr/bin/build-classpath: Could not find jline2 Java extension for this JVM
    /usr/bin/build-classpath: error: Some specified jars were not found
    java.lang.NoClassDefFoundError: jline/TerminalFactory
	    at sbt.ConsoleLogger$.ansiSupported(ConsoleLogger.scala:86)
	    at sbt.ConsoleLogger$.<init>(ConsoleLogger.scala:80)
	    at sbt.ConsoleLogger$.<clinit>(ConsoleLogger.scala)
	    at sbt.GlobalLogging$.initial(GlobalLogging.scala:40)
	    at sbt.StandardMain$.initialGlobalLogging(Main.scala:64)
	    at sbt.StandardMain$.initialState(Main.scala:73)
	    at sbt.xMain.run(Main.scala:29)
	    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
	    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
	    at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
	    at xsbt.boot.Launch$.run(Launch.scala:57)
	    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
	    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
	    at xsbt.boot.Launch$.launch(Launch.scala:65)
	    at xsbt.boot.Launch$.explicit(Launch.scala:45)
	    at xsbt.boot.Launch$.initialized(Launch.scala:41)
	    at xsbt.boot.Launch$.parsed(Launch.scala:34)
	    at xsbt.boot.Launch$.configured(Launch.scala:24)
	    at xsbt.boot.Launch$.apply(Launch.scala:19)
	    at xsbt.boot.Launch$.apply(Launch.scala:16)
	    at xsbt.boot.Boot$.runImpl(Boot.scala:32)
	    at xsbt.boot.Boot$.run(Boot.scala:26)
	    at xsbt.boot.Boot$.main(Boot.scala:21)
	    at xsbt.boot.Boot.main(Boot.scala)

After this, I click on the RPM link on the sbt linux getting started page, and it downloads 
the  rpm for sbt 13.16.  I run

# dnf install sbt-0.13.16.rpm

This show, among other messages:

    Upgrading:
        sbt          noarch          0.13.16-0             @commandline          1.0 M

It runs a while, with the modem showing lots more is getting downloaded.  Then says:

    Complete!
    
However,  testing if it worked gives this:

# sbt
bash: sbt: command not found...
Install package 'sbt' to provide command 'sbt'? [N/y]


I try to find where sbt has been installed:

# find / -name sbt | grep sbt$ | more
This gives a list of about 15 files, including some under /nix, which I am not currently very hot on, some perhaps from old installations, with these the most promising

    1.  /home/al/.sbt/boot/scala-2.10.4/org.scala-sbt/sbt   
    
        This is a folder, apparently related to sbt-0.13.1, not sbt-0.13.16
        
    2.  /root/.sbt/boot/scala-2.10.6/org.scala-sbt/sbt
    
        This is also a  folder, apparently related to sbt-0.13.16.  
        The folder contains sbt-0.13.16.jar, but not sbt.
        
    
    3. /root/.sbt/boot/scala-2.10.4/org.scala-sbt/sbt
    
        This is a folder, apparently related to sbt-0.13.1, not sbt-0.13.16, i.e. maybe the 
        same as (1) above.
        
    4.   /usr/share/sbt/bin/sbt
    
        This says it is an executable file, but the date is 6 months old.  I try running it:
        
        #  /usr/share/sbt/bin/sbt
            [info] Updated file /root/project/build.properties: set sbt.version to 0.13.16
            [info] Loading project definition from /root/project
            [info] Updating {file:/root/project/}root-build...
            WARNING: An illegal reflective access operation has occurred
            WARNING: Illegal reflective access by sbt.ivyint.ErrorMessageAuthenticator$ 
                (file:/root/.sbt/boot/scala-2.10.6/org.scala-sbt/sbt/0.13.16/ivy-0.13.16.jar) to field
                     java.net.Authenticator.theAuthenticator
            WARNING: Please consider reporting this to the maintainers of
                 sbt.ivyint.ErrorMessageAuthenticator$
            WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective
                 access operations
            WARNING: All illegal access operations will be denied in a future release
            [info] Resolving org.fusesource.jansi#jansi;1.4 ...
            [info] downloading 
                https://repo.typesafe.com/typesafe/ivy-releases/org.scala-tools.sbinary/
                    sbinary_2.10/0.4.2/jars/sbinary_2.10.jar ...
            [info] 	[SUCCESSFUL ] org.scala-tools.sbinary#sbinary_2.10;0.4.2!sbinary_2.10.jar
                     (3788ms)
            [info] downloading 
                https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-
                               interface-1.0.jar ...
            [info] 	[SUCCESSFUL ] org.scala-sbt#test-interface;1.0!test-interface.jar (442ms)
            [info] Done updating.
            [info] Set current project to root (in build file:/root/
        
        I copy the file to a location on my path:
        
            # cp /usr/share/sbt/bin/sbt /usr/local/bin
            # sbt 
            
        This fails:
            /usr/local/bin/sbt: line 61: /usr/local/bin/sbt-launch-lib.bash: No such file or directory
            /usr/local/bin/sbt: line 153: run: command not found
            
        I put this into /usr/bin/sbt
        
            #! /usr/bin/bash
            /usr/share/sbt/bin/sbt            
            
        I run
        
            $ sudo chmod 0755 /usr/bin/bash
            
        Now I think that I have sbt in and running OK???

**Comment by eed3si9n** [comment] 2019-08-02 17:15
I am closing this due to inactivity, but if this is still relevant let us know with more details (reproduction steps etc).

**Closed by eed3si9n** 2019-08-02 17:15 UTC
Labels: Bug
