### ISSUE TITLE
The repository 'https://dl.bintray.com/sbt/debian  Release' is no longer signed.

### ISSUE THREAD

**Issue by jjudd** [sbt/sbt-launcher-package#252] opened 2019-01-08 00:46 UTC
Me and several colleagues started seeing this error recently when running `apt update` on Ubuntu.

```
E: The repository 'https://dl.bintray.com/sbt/debian  Release' is no longer signed.
```

Curious if we missed a key change or something like that?

**Comment by eed3si9n** [comment] 2019-01-08 01:50
Yes, it should be fixed now.
Duplicate of https://github.com/sbt/sbt/issues/4507.

**Closed by eed3si9n** 2019-01-08 01:50 UTC
